---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      chart: jackett
      version: 11.7.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  dependsOn:
    - name: nfs-subdir-external-provisioner
      namespace: storage
    - name: cert-manager
      namespace: networking
    - name: ingress-nginx
      namespace: networking
  values:
    image:
      repository: linuxserver/jackett
      tag: development-version-v0.18.532
    env:
      TZ: "${TIMEZONE}"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          hajimari.io/enable: 'true'
          hajimari.io/icon: hanger
          hajimari.io/group: Internal
        hosts:
          - host: "jackett.${DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "jackett.${DOMAIN}"
            secretName: jackett-tls
    persistence:
      config:
        enabled: true
        storageClass: nfs-kube
      torrentblackhole:
        enabled: false
        mountPath: /downloads
